name: flutter_project_ready
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  fl_chart: ^1.1.1

  # State management
  provider: ^6.1.2

  # Data / storage / security
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  crypto: ^3.0.6

  # Auth & encryption
  local_auth: ^2.2.1
  argon2: ^1.0.0
  dargon2: ^3.2.1

  # Backend / networking
  http: ^1.5.0
  uuid: ^3.0.7
  mailer: ^6.6.0
  web3dart: ^2.6.1
  url_launcher: ^6.1.10

  # ⭐⭐⭐ Firebase packages (مضافة حديثاً)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
