// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBayzrOpTGtL9WMGLRdEUpCBON1NivfY9w',
    appId: '1:139315326805:web:5285818839b7a2c241c9dc',
    messagingSenderId: '139315326805',
    projectId: 'flutter-login-app-2025',
    authDomain: 'flutter-login-app-2025.firebaseapp.com',
    storageBucket: 'flutter-login-app-2025.firebasestorage.app',
    measurementId: 'G-EPPG6JJV4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKrQWcMNcWf-8UMVJTyDVkltWPBT2FQzg',
    appId: '1:139315326805:android:ca6bcff810aed28641c9dc',
    messagingSenderId: '139315326805',
    projectId: 'flutter-login-app-2025',
    storageBucket: 'flutter-login-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55pBGW6Vrp79heOoMci7E50nAG79-c0w',
    appId: '1:139315326805:ios:52006bf5b9b6682f41c9dc',
    messagingSenderId: '139315326805',
    projectId: 'flutter-login-app-2025',
    storageBucket: 'flutter-login-app-2025.firebasestorage.app',
    iosClientId: '139315326805-jqub1dsuma87b0sjhfi5l0o9onm05sqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectReady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB55pBGW6Vrp79heOoMci7E50nAG79-c0w',
    appId: '1:139315326805:ios:52006bf5b9b6682f41c9dc',
    messagingSenderId: '139315326805',
    projectId: 'flutter-login-app-2025',
    storageBucket: 'flutter-login-app-2025.firebasestorage.app',
    iosClientId: '139315326805-jqub1dsuma87b0sjhfi5l0o9onm05sqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectReady',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBayzrOpTGtL9WMGLRdEUpCBON1NivfY9w',
    appId: '1:139315326805:web:4aab3345d0a7845841c9dc',
    messagingSenderId: '139315326805',
    projectId: 'flutter-login-app-2025',
    authDomain: 'flutter-login-app-2025.firebaseapp.com',
    storageBucket: 'flutter-login-app-2025.firebasestorage.app',
    measurementId: 'G-YK2HBYWT50',
  );
}
